### ISSUE TITLE
Project 1 - Personal Portfolio

### ISSUE THREAD

**Issue by camerican** [camerican/NYCDA_SCC16_Christian#11]
Project 1 has the following requirements:
- [x] At least 3 separate pages +
- [ ] Connected by a consistent navigation menu (3)
- [ ] Uses CSS layout principles, with design-friendly whitespace (6)
- [x] Includes images (2)
- [ ] Has links to external websites that open in a new window
- [x] Incorporates a ul and nav powered navigation bar (2)
- [ ] Overall quality of the site (3)
- [ ] Is well committed and pushed to GitHub (3)

**Comment by camerican** [comment]
The following issues are outstanding:
- [ ] Navigation wraps to new line as viewport narrows #13
- [ ] Images are left-aligned as viewport narrows #14
- [ ] Absolute links to file:// locations #12 
- [ ] Contact page image jumps down as viewport narrows #15
- [ ] Placeholder text should be removed #16

**Comment by sarabet123** [comment]
So what are u asking me to do

**Comment by camerican** [comment]
Issues #12, #13, #14, #15, and #16 could use fixing on this assignment.  If you're happy with your current grade, then there's no need to make any changes.  You also have the option to resubmit the assignment via GitHub.
